version: '3'

services:
  db:
    image: docker.io/redis
    container_name: db
    restart: always
    ports:
      - 6379:6379
  server:
    depends_on:
      - db
    restart: always
    build: ./backend/
    container_name: server
    ports:
      - 3000:3000

